server:
   port: 4444
 
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/sps_test?createDatabaseIfNotExist=true
      username: root 
      password: root
   
   jpa:
      show-sql: true
      ## Data Definition properties
      hibernate:
         ddl-auto: create
      properties:
         dialect: org.hibernate.dialect.MySQL5Dialect
   
   mail:
      host: smtp.gmail.com
      port: 587
      username: dspnadendla@gmail.com
      password: bmtytiyprmpyhwzi      
      properties.mail.smtp.auth: true
      properties.mail.smtp.starttls.enable: true


#   mvc:
#      throw-exception-if-no-handler-found: true # Specifying to throw excecption if no handler method is found
#   resources:
#      add-mappings: false # Specifying to disable mapping to /error path

jwt:
   secret: '@PASS@'